# Generated by Django 6.0a1 on 2025-10-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='NasaApp_act_name_387192_idx'), models.Index(fields=['slug'], name='NasaApp_act_slug_f5737f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('unit', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='NasaApp_wea_code_75d0b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='NasaApp.activity')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='NasaApp.weatherparam')),
            ],
            options={
                'indexes': [models.Index(fields=['activity', 'param'], name='NasaApp_act_activit_9ea5ee_idx')],
                'unique_together': {('activity', 'param')},
            },
        ),
    ]
